# Generated by Django 5.2.4 on 2025-07-24 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BitnobCustomer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=20)),
                ("country_code", models.CharField(max_length=5)),
                ("bitnob_id", models.CharField(max_length=100, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="receiver",
            name="schedule",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="schedule",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="receiver",
        ),
        migrations.CreateModel(
            name="MobileReceiver",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=20)),
                ("country_code", models.CharField(max_length=5)),
                (
                    "amount_per_installment",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("number_of_installments", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receivers",
                        to="payments.bitnobcustomer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MobileTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("installment_number", models.PositiveIntegerField()),
                ("status", models.CharField(default="pending", max_length=20)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "receiver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="payments.mobilereceiver",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="PaymentSchedule",
        ),
        migrations.DeleteModel(
            name="Receiver",
        ),
        migrations.DeleteModel(
            name="Transaction",
        ),
    ]
