# Generated by Django 5.2.4 on 2025-07-24 13:55

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_bitnobcustomer_remove_receiver_schedule_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mobiletransaction",
            options={"ordering": ["receiver", "installment_number"]},
        ),
        migrations.AddField(
            model_name="mobiletransaction",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mobiletransaction",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=567),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mobiletransaction",
            name="failure_reason",
            field=models.TextField(
                blank=True, help_text="Reason for failure if transaction failed"
            ),
        ),
        migrations.AddField(
            model_name="mobiletransaction",
            name="reference",
            field=models.CharField(
                blank=True,
                help_text="Bitnob transaction reference",
                max_length=100,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="mobiletransaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("success", "Success"),
                    ("failed", "Failed"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="mobiletransaction",
            unique_together={("receiver", "installment_number")},
        ),
        migrations.CreateModel(
            name="PaymentSchedule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Descriptive name for this payment schedule",
                        max_length=200,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Optional description of the payment plan"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("paused", "Paused"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total amount across all receivers and installments",
                        max_digits=15,
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        default="monthly",
                        help_text="Payment frequency (e.g., weekly, monthly)",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "end_date",
                    models.DateTimeField(
                        blank=True, help_text="Expected completion date", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_schedules",
                        to="payments.bitnobcustomer",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="mobilereceiver",
            name="payment_schedule",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="receivers",
                to="payments.paymentschedule",
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="mobilereceiver",
            unique_together={("payment_schedule", "phone")},
        ),
    ]
