# Generated by Django 5.2.4 on 2025-07-24 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0004_migrate_existing_receivers"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentschedule",
            name="subtotal_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Subtotal amount across all receivers and installments (before processing fee)",
                max_digits=15,
            ),
        ),
        migrations.AddField(
            model_name="paymentschedule",
            name="processing_fee",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Processing fee (1.5% of subtotal)",
                max_digits=15,
            ),
        ),
        migrations.AlterField(
            model_name="paymentschedule",
            name="total_amount",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Total amount including processing fee",
                max_digits=15,
            ),
        ),
    ]
