# Generated by Django 5.2.4 on 2025-07-24 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0005_add_processing_fee_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mobilereceiver",
            name="payment_schedule",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="receivers",
                to="payments.paymentschedule",
            ),
        ),
        migrations.AlterField(
            model_name="mobiletransaction",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="paymentschedule",
            name="subtotal_amount",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Subtotal amount across all receivers and installments (before processing fee)",
                max_digits=15,
            ),
        ),
    ]
