# Generated by Django 5.2.4 on 2025-07-24 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0006_add_unique_phone_per_schedule"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mobilereceiver',
            unique_together={('payment_schedule', 'phone')},
        ),
    ]
