# Generated by Django 5.2.4 on 2025-07-24 20:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0007_add_phone_unique_constraint"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentschedule",
            name="is_funded",
            field=models.BooleanField(
                default=False,
                help_text="Whether this schedule has been adequately funded",
            ),
        ),
        migrations.CreateModel(
            name="FundTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("reference", models.CharField(max_length=100, unique=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=20)),
                ("currency", models.CharField(default="UGX", max_length=10)),
                (
                    "stablecoin_address",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "stablecoin_network",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "usdt_required",
                    models.DecimalField(decimal_places=6, max_digits=20, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("paid", "Paid"),
                            ("expired", "Expired"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fund_transactions",
                        to="payments.paymentschedule",
                    ),
                ),
            ],
        ),
    ]
