# Generated by Django 5.2.4 on 2025-07-25 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0008_paymentschedule_is_funded_fundtransaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentschedule",
            name="last_payment_date",
            field=models.DateTimeField(
                blank=True, help_text="When the last payment was processed", null=True
            ),
        ),
        migrations.AddField(
            model_name="paymentschedule",
            name="next_payment_date",
            field=models.DateTimeField(
                blank=True,
                help_text="When the next payment should be processed",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="paymentschedule",
            name="frequency",
            field=models.CharField(
                default="monthly",
                help_text="Payment frequency (e.g., test_2min, weekly, monthly)",
                max_length=20,
            ),
        ),
    ]
